package pe.mil.microservices.dtos;

import com.fasterxml.jackson.annotation.JsonInclude;
import lombok.*;

import java.io.Serializable;

@Data
@Builder
@ToString
@AllArgsConstructor
@NoArgsConstructor
@JsonInclude(JsonInclude.Include.NON_NULL)
public class StandardTransaction implements Serializable {

    private static final long serialVersionUID = 5230901019196076390L;
    private String messageTypeIndicator;
    private String dataElement_2;
    private String dataElement_3;
    private String dataElement_4;
    private String dataElement_5;
    private String dataElement_7;
    private String dataElement_9;
    private String dataElement_11;
    private String dataElement_12;
    private String dataElement_13;
    private String dataElement_14;
    private String dataElement_15;
    private String dataElement_16;
    private String dataElement_18;
    private String dataElement_22;
    private String dataElement_23;
    private String dataElement_25;
    private String dataElement_26;
    private String dataElement_27;
    private String dataElement_28;
    private String dataElement_29;
    private String dataElement_30;
    private String dataElement_31;
    private String dataElement_32;
    private String dataElement_33;
    private String dataElement_35;
    private String dataElement_37;
    private String dataElement_38;
    private String dataElement_39;
    private String dataElement_40;
    private String dataElement_41;
    private String dataElement_42;
    private String dataElement_43;
    private String dataElement_44;
    private String dataElement_45;
    private String dataElement_48;
    private String dataElement_49;
    private String dataElement_50;
    private String dataElement_52;
    private String dataElement_53;
    private String dataElement_54;
    private String dataElement_56;
    private String dataElement_57;
    private String dataElement_58;
    private String dataElement_59;
    private String dataElement_66;
    private String dataElement_67;
    private String dataElement_70;
    private String dataElement_73;
    private String dataElement_74;
    private String dataElement_75;
    private String dataElement_76;
    private String dataElement_77;
    private String dataElement_78;
    private String dataElement_79;
    private String dataElement_80;
    private String dataElement_81;
    private String dataElement_82;
    private String dataElement_83;
    private String dataElement_84;
    private String dataElement_85;
    private String dataElement_86;
    private String dataElement_87;
    private String dataElement_88;
    private String dataElement_89;
    private String dataElement_90;
    private String dataElement_91;
    private String dataElement_95;
    private String dataElement_97;
    private String dataElement_98;
    private String dataElement_100;
    private String dataElement_101;
    private String dataElement_102;
    private String dataElement_103;
    private String dataElement_118;
    private String dataElement_119;
    private String dataElement_123;
    private String dataElement_127_2;
    private String dataElement_127_3;
    private String dataElement_127_4;
    private String dataElement_127_5;
    private String dataElement_127_6;
    private String dataElement_127_7;
    private String dataElement_127_8;
    private String dataElement_127_9;
    private String dataElement_127_10;
    private String dataElement_127_11;
    private String dataElement_127_12;
    private String dataElement_127_13;
    private String dataElement_127_14;
    private String dataElement_127_15;
    private String dataElement_127_16;
    private String dataElement_127_17;
    private String dataElement_127_18;
    private String dataElement_127_19;
    private String dataElement_127_20;
    private String dataElement_127_21;
    private String dataElement_127_22;
    private String dataElement_127_23;
    private String dataElement_127_24;
    private String dataElement_127_25;
    private String dataElement_127_26;
    private String dataElement_127_27;
    private String dataElement_127_28;
    private String dataElement_127_29;
    private String dataElement_127_30;
    private String dataElement_127_31;
    private String dataElement_127_32;
    private String dataElement_127_33;
    private String dataElement_127_34;
    private String dataElement_127_35;
    private String dataElement_127_36;
    private String dataElement_127_37;
    private String dataElement_127_38;
    private String dataElement_127_39;
    private String dataElement_127_40;
    private String dataElement_127_41;
    private String dataElement_127_42;
    private String dataElement_127_43;
    private String dataElement_127_44;
    private String dataElement_127_45;
    private String dataElement_127_46;
    private String dataElement_127_47;
    private String dataElement_127_48;
    private String dataElement_127_49;
    private String dataElement_127_55;
    private String dataElement_127_56;
    private String dataElement_127_57;
    private String dataElement_127_58;
}